import { MainNav } from "@/components/MainNav";
import { Button } from "@/components/ui/button";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menu = [
  {
    title: "Products",
    href: "/dashboard/products",
  },
  {
    title: "Category",
    href: "/dashboard/category",
  },
];

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="hidden flex-col md:flex">
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <MainNav items={menu} />
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
